### ISSUE TITLE
USER：安卓系統5.1.1版本，Sony Z1compact不會唸單字，要加進清單還會直接程式停止

### ISSUE THREAD

**Issue by h94g41up** [WishCanTaiwan/VocabuLazy#111]

**Comment by swallowchen1359** [comment]
加進清單會直接停止應該在已經在VocabuLazy alpha解決。
https://play.google.com/store/apps/details?id=wishcantw.vocabulazy.alpha
不會念單字是否是他沒有安裝google語音
