### ISSUE TITLE
使用者反映測驗部分的題目一直重複

### ISSUE THREAD

**Issue by swallowchen1359** [WishCanTaiwan/VocabuLazy#132]
單元練習一直重複1～5的呢？6後面的都沒有題目
就是單元6的題目其實是單元1的單字/單元7的題目其實是單元2的單字⋯單元32的題目其實是單元2的單字

**Comment by swallowchen1359** [comment]
無法在Android手機上重現
後來用戶指出是iOS系統
已指定阿呆幫忙確認

**Comment by bcbod2002** [comment]
是 iOS 這邊的問題沒錯
