### ISSUE TITLE
Need to remind user what are the updates

### ISSUE THREAD

**Issue by ylallencheng** [WishCanTaiwan/VocabuLazy#38]
please show dialog and list updates to user while entering main menu.

**Comment by ylallencheng** [comment]
step 1: read a config from internal storage which stores the version code
step 2.1: if filenotfoundexception caught, then show nothing and create a config with version code
step 2.2: if config found, check the version code
step 2.2.1: if version code match the latest, return
step 2.2.2: if version code is older, show update dialog and update version code in config

**Comment by swallowchen1359** [comment]
Do you finish it completely? @allencheng07

**Comment by ylallencheng** [comment]
yes

**Comment by swallowchen1359** [comment]
good
