### ISSUE TITLE
Tapping on Player Item will cause reseting the repeat count of that vocabulary

### ISSUE THREAD

**Issue by ylallencheng** [WishCanTaiwan/VocabuLazy#44]
As titled, this should not happened. The repeat count should only be reset while scrolling to other item, switching to other lesson or changing the repeat count setting in OptionSettings

**Comment by swallowchen1359** [comment]
@allencheng07 Please directly use new PlayerOption design to figuring out the issue.

**Comment by swallowchen1359** [comment]
@allencheng07 
How about trying the new thought? Make vertical scroll and horizontal scroll follow the same rule.
1. If vertical scroll doesn't change focused item, do not pause. (If currently playing)
2. Else, pause until new item is focused.
3. If horizontal scroll doesn't exceed the "page scrolled" limit, do not pause. (If currently playing)
4. Else, i.e., onPageScrolled triggered, pause until the pageScrolled animation done, i.e., onPageScrollStop triggered.

I will add new api and have a pull request maybe tomorrow.
