### ISSUE TITLE
測驗功能的喇叭按鈕沒有功能

### ISSUE THREAD

**Issue by swallowchen1359** [WishCanTaiwan/VocabuLazy#73]
按下去應該要有聲音！

**Comment by swallowchen1359** [comment]
Hi @allencheng07 
Please help me to verify the pull request #81 
https://github.com/WishCanTaiwan/VocabuLazy/pull/81
After merge, please complete the following steps and leave the msg here to me.
Thanks

**Comment by swallowchen1359** [comment]
@allencheng07 Did we solve the issue??

**Comment by ylallencheng** [comment]
@swallowchen1359 solved

**Comment by swallowchen1359** [comment]
@allencheng07 Thanks
