### ISSUE TITLE
播放期間，新增清單，造成crash

### ISSUE THREAD

**Issue by swallowchen1359** [WishCanTaiwan/VocabuLazy#85]
step: 
1. 選擇"自訂清單1"播放，進入PLAYER
2. 暫停播放
3. 離開PLAYER
4. 進入SEARCH
5. 新增單字到"自訂清單1"
6. 選擇"自訂清單1"，進入PLAYER
7. 移動到剛剛新增的單字
8. Crash, Caused by: java.lang.IndexOutOfBoundsException: Invalid index 7, size is 7

**Comment by swallowchen1359** [comment]
可能是AudioService或者Player吃的array沒有更新

**Comment by ylallencheng** [comment]
@swallowchen1359 I'll try whether this still happens under the new structure

**Comment by swallowchen1359** [comment]
Thanks

**Comment by swallowchen1359** [comment]
Thanks
