### ISSUE TITLE
Pull Request #87 造成暫停後再次播放，會播放原本暫停的單字而不是新單字

### ISSUE THREAD

**Issue by swallowchen1359** [WishCanTaiwan/VocabuLazy#88]
#87 會造成a單字暫停後，移動到b單字，卻是播放a單字內容的情況。

**Comment by swallowchen1359** [comment]
@allencheng07 Did you solve the problem ??

**Comment by ylallencheng** [comment]
@swallowchen1359 not yet

**Comment by swallowchen1359** [comment]
OK

**Comment by ylallencheng** [comment]
@swallowchen1359 the issue is reported days ago and I cannot reproduce the bug, so I think we can considered it as solved. If you cannot reproduce as well and have no other issue, we can close this issue!

**Comment by swallowchen1359** [comment]
@allencheng07 I'll try it later. Thanks

**Comment by swallowchen1359** [comment]
@allencheng07  I can NOT reproduce either. Thanks
